"""Self-contained HTML report export for ContractGuard analyses."""

from __future__ import annotations

import html

from contractguard.models import AnalysisResult, Issue, Protection

_GRADE_HEX = {
    "A+": "#16a34a", "A": "#16a34a", "B+": "#4d7c0f", "B": "#ca8a04",
    "C+": "#ca8a04", "C": "#ea580c", "D": "#dc2626", "F": "#b91c1c",
}

_CSS = """
body { font-family: -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
       margin: 0; background: #f8fafc; color: #0f172a; }
.page { max-width: 760px; margin: 0 auto; padding: 32px 20px 48px; }
.header { background: #fff; border: 1px solid #e2e8f0; border-radius: 12px;
          padding: 24px 28px; margin-bottom: 24px; }
.header h1 { font-size: 22px; margin: 0 0 8px; }
.meta { color: #475569; font-size: 14px; margin: 2px 0; }
.grade { display: inline-block; font-weight: 700; font-size: 15px; color: #fff;
         border-radius: 999px; padding: 4px 14px; margin-top: 10px; }
.scorebar { height: 8px; border-radius: 999px; background: #e2e8f0; margin-top: 12px; }
.scorefill { height: 8px; border-radius: 999px; }
h2 { font-size: 17px; margin: 28px 0 12px; }
.card { background: #fff; border: 1px solid #e2e8f0; border-left: 4px solid #94a3b8;
        border-radius: 8px; padding: 16px 20px; margin: 12px 0; }
.card h3 { font-size: 15px; margin: 0 0 8px; }
.card.red { border-left-color: #dc2626; }
.card.yellow { border-left-color: #ca8a04; }
.card.green { border-left-color: #16a34a; }
.clause { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: .04em; }
.quote { background: #f1f5f9; border-radius: 6px; padding: 10px 14px; font-size: 14px;
         font-style: italic; color: #334155; margin: 10px 0; }
.label { font-weight: 600; font-size: 14px; }
.terms li, .missing li { margin: 6px 0; }
.footer { margin-top: 36px; color: #94a3b8; font-size: 12px; text-align: center; }
"""


def _esc(text: object) -> str:
    """Escape user/contract text for safe inline HTML."""
    return html.escape(str(text), quote=True)


def _issue_card(issue: Issue, kind: str) -> str:
    return f"""
    <div class="card {kind}">
      <h3>{_esc(issue.title)}</h3>
      <div class="clause">{_esc(issue.clause)}</div>
      <div class="quote">{_esc(issue.quote)}</div>
      <p>{_esc(issue.explanation)}</p>
      <p><span class="label">Suggestion:</span> {_esc(issue.suggestion)}</p>
    </div>"""


def _protection_card(protection: Protection) -> str:
    return f"""
    <div class="card green">
      <h3>{_esc(protection.title)}</h3>
      <div class="clause">{_esc(protection.clause)}</div>
      <p>{_esc(protection.explanation)}</p>
    </div>"""


def generate_html_report(result: AnalysisResult) -> str:
    """Render a self-contained HTML report (inline CSS, no external resources)."""
    grade_color = _GRADE_HEX.get(result.fairness_grade, "#475569")
    score = max(0, min(100, result.fairness_score))

    key_terms = "".join(f"<li>{_esc(t)}</li>" for t in result.key_terms)
    red_cards = "".join(_issue_card(i, "red") for i in result.red_flags)
    warn_cards = "".join(_issue_card(i, "yellow") for i in result.warnings)
    good_cards = "".join(_protection_card(p) for p in result.good_clauses)
    missing = "".join(f"<li>{_esc(m)}</li>" for m in result.missing_protections)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ContractGuard Report — {_esc(result.contract_type.value.replace('_', ' ').title())}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="page">
  <div class="header">
    <h1>ContractGuard Analysis Report</h1>
    <div class="meta">Contract type: {_esc(result.contract_type.value.replace('_', ' ').title())}</div>
    <div class="meta">Parties: {_esc(', '.join(result.parties) or '—')}</div>
    <div class="grade" style="background:{grade_color}">{_esc(result.fairness_grade)} · {score}/100</div>
    <div class="scorebar"><div class="scorefill" style="width:{score}%;background:{grade_color}"></div></div>
  </div>

  <h2>Summary</h2>
  <p>{_esc(result.summary)}</p>

  {"<h2>Key Terms</h2><ul class='terms'>" + key_terms + "</ul>" if key_terms else ""}
  {"<h2>Red Flags</h2>" + red_cards if red_cards else ""}
  {"<h2>Warnings</h2>" + warn_cards if warn_cards else ""}
  {"<h2>Good Clauses</h2>" + good_cards if good_cards else ""}
  {"<h2>Missing Protections</h2><ul class='missing'>" + missing + "</ul>" if missing else ""}

  <div class="footer">Generated by ContractGuard — never sign a bad contract again.</div>
</div>
</body>
</html>
"""
